### ISSUE TITLE
[DataHub]: using FireFox 115.1.0 (or upper), WFS issues

### ISSUE THREAD

**Issue by mvadin** [geonetwork/geonetwork-ui#572] opened 2023-08-10 12:01 UTC
WFS features (Table view / zoom Map)do not work fine with FireFox 115.1.0 (or upper).

Browser console reports Warning 8298/getDownloadUrlsFromWfs...

![image](https://github.com/geonetwork/geonetwork-ui/assets/19262235/ce23ee8e-177c-43f8-8a61-7a17ed2c193d)

URL : https://www.datagrandest.fr/datahub/dataset/FR-200052264-Commune_Grand_Est

Regards

**Comment by jahow** [comment] 2023-08-11 08:55
Tried with Firefox 116 locally and it worked:
![image](https://github.com/geonetwork/geonetwork-ui/assets/10629150/d2013851-1c62-4e6c-b605-8a62cf077b92)

Could you give more information to help us figure out the issue?
* using private mode or not?
* any failures in the network requests going to the WFS service?

Thanks

**Comment by mvadin** [comment] 2023-08-11 09:08
Thank you for the answer,

Working fine in 116 but not in private mode.

Regards

**Comment by fgravin** [comment] 2023-12-12 13:17
It seems that FF in Private browsing has an issue reading/writing to **cache Storage**.
Here the error:

```
Uncaught (in promise) DOMException: **The operation is insecure**.
    4505 https://www.datagrandest.fr/datahub/main.7acf17b8ce68852b.js:133
    r https://www.datagrandest.fr/datahub/runtime.4381662fc90e13c0.js:1
    <anonymous> https://www.datagrandest.fr/datahub/main.7acf17b8ce68852b.js:133
    n https://www.datagrandest.fr/datahub/runtime.4381662fc90e13c0.js:1
    <anonymous> https://www.datagrandest.fr/datahub/main.7acf17b8ce68852b.js:1
```

**Comment by fgravin** [comment] 2023-12-12 13:24
The issue is on the OGC client side
See upstream PR https://github.com/camptocamp/ogc-client/issues/15

**Comment by jahow** [comment] 2024-01-18 09:48
Issue has been fixed in ogc-client, the problem should disappear in geonetwork-ui once we update the library

**Comment by jahow** [comment] 2024-05-17 08:34
ogc-client has been updated, I'm closing this issue; please reopen if the issue persists!

**Closed by jahow** 2024-05-17 08:34 UTC
Labels: bug
